spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: baidu-route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq-route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
#商品服务路由配置
        - id: product-route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: oss_route
          uri: lb://mall-oss
          predicates:
            - Path=/api/oss/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
## 前端项目发送的接口都带上/api前缀
## http://localhost:88/api/captcha.jpg  ====>http://localhost/renren-fast/captcha.jpg
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
server:
  port: 88